apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pizza-castle-dev
resources:
  - ../../bases/pizza-castle-web
  - ../../bases/pizza-castle-menu-service
  - ../../bases/pizza-castle-ordering-service
  - ../../bases/pizza-castle-ingress
  - namespace.yaml
replicas:
  - count: 1
    name: pizza-castle-web
  - count: 1
    name: pizza-castle-menu-service
  - count: 1
    name: pizza-castle-ordering-service
images:
  - name: kajendranalagaratnam/pizza-castle-web
    newTag: dev-b3d2b99-1643720805 # {"$imagepolicy": "flux-system:web-image-policy:tag"}
  - name: gayankanishka/pizza-castle-menu-service
    newTag: dev-973c3b1-1640925237 # {"$imagepolicy": "flux-system:menu-service-image-policy:tag"}
  - name: gayankanishka/pizza-castle-ordering-service
    newTag: dev-b6ae829-1640870418 # {"$imagepolicy": "flux-system:ordering-service-image-policy:tag"}
configMapGenerator:
  - name: auth-secret
    env: config.properties
  - name: auth0-base-url
    env: config.properties
  - name: auth0-issuer-base-url
    env: config.properties
  - name: auth0-audience
    env: config.properties
  - name: auth0-client-id
    env: config.properties
  - name: auth0-client-secret
    env: config.properties
  - name: order-base-url
    env: config.properties
  - name: menu-base-url
    env: config.properties
  - name: use-in-memory-db
    env: config.properties
  - name: asp-net-core-env
    env: config.properties
