apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pizza-castle-dev
resources:
  - ../../bases/pizza-castle-web
  - ../../bases/pizza-castle-menu-service
  - ../../bases/pizza-castle-ordering-service
  - ../../bases/pizza-castle-ingress
  - namespace.yaml
replicas:
  - count: 1
    name: pizza-castle-web
  - count: 1
    name: pizza-castle-menu-service
  - count: 1
    name: pizza-castle-ordering-service
images:
  - name: kajendranalagaratnam/pizza-castle-web
    newTag: dev-8b7371c-1640864567 # {"$imagepolicy": "flux-system:web-image-policy:tag"}
  - name: gayankanishka/pizza-castle-menu-service
    newTag: dev-34a3d71-1640865985 # {"$imagepolicy": "flux-system:menu-service-image-policy:tag"}
  - name: gayankanishka/pizza-castle-ordering-service
    newTag: latest # {"$imagepolicy": "flux-system:ordering-service-image-policy:tag"}
