apiVersion: v1
data:
  AUTH0_SECRET: ''
  AUTH0_BASE_URL: ''
  AUTH0_ISSUER_BASE_URL: ''
  AUTH0_AUDIENCE: ''
  AUTH0_CLIENT_ID: ''
  AUTH0_CLIENT_SECRET: ''
  ORDER_BASE_URL: ''
  MENU_BASE_URL: ''
kind: ConfigMap
metadata:
  name: web-config-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-castle-web
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    app: pizza-castle-web
annotations:
  fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: pizza-castle-web
  replicas: 1
  template:
    metadata:
      labels:
        app: pizza-castle-web
    spec:
      containers:
        - name: web-app
          image: kajendranalagaratnam/pizza-castle-web
          env:
            - name: AUTH0_SECRET
              valueFrom:
                configMapKeyRef:
                  name: auth-secret
                  key: AUTH0_SECRET
            - name: AUTH0_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth0-base-url
                  key: AUTH0_BASE_URL
            - name: AUTH0_ISSUER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth0-issuer-base-url
                  key: AUTH0_ISSUER_BASE_URL
            - name: AUTH0_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: auth0-audience
                  key: AUTH0_AUDIENCE
            - name: AUTH0_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: auth0-client-id
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: auth0-client-secret
                  key: AUTH0_CLIENT_SECRET
            - name: ORDER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-base-url
                  key: ORDER_BASE_URL
            - name: MENU_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: menu-base-url
                  key: MENU_BASE_URL
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pizza-castle-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: pizza-castle-web
