apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pizza-castle-prod
resources:
  - ../../bases/pizza-castle-web
  - ../../bases/pizza-castle-menu-service
  - ../../bases/pizza-castle-ordering-service
  - ../../bases/pizza-castle-ingress
  - namespace.yaml
replicas:
  - count: 10
    name: pizza-castle-web
  - count: 10
    name: pizza-castle-menu-service
  - count: 10
    name: pizza-castle-ordering-service
images:
  - name: kajendranalagaratnam/pizza-castle-web:main
  - name: gayankanishka/pizza-castle-menu-service:latest
  - name: gayankanishka/pizza-castle-ordering-service:latest
configMapGenerator:
  - name: auth-secret
    env: config.properties
  - name: auth0-base-url
    env: config.properties
  - name: auth0-issuer-base-url
    env: config.properties
  - name: auth0-audience
    env: config.properties
  - name: auth0-client-id
    env: config.properties
  - name: auth0-client-secret
    env: config.properties
  - name: order-base-url
    env: config.properties
  - name: menu-base-url
    env: config.properties
  - name: use-in-memory-db
    env: config.properties
  - name: asp-net-core-env
    env: config.properties