apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-castle-web
annotations:
  fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      name: pizza-castle-web
  template:
    metadata:
      labels:
        name: pizza-castle-web
    spec:
      containers:
        - name: web
          image: kajendranalagaratnam/pizza-castle-web:main
          ports:
            - containerPort: 3000
          env:
            - name: AUTH0_SECRET
              value: 'bbea652bf473d0cbdd843e5f32eb2cf0c8698f6ea5f7809e84616d5ecf7d4d55'
            - name: AUTH0_BASE_URL
              value: 'http://k8s-default-pizzacas-965b4a9f76-1648152203.eu-west-1.elb.amazonaws.com'
            - name: AUTH0_ISSUER_BASE_URL
              value: 'https://dev-pizza-castle.us.auth0.com'
            - name: AUTH0_CLIENT_ID
              value: e4V40isp8iT4fcLkX6RasFKmqSNmesnG
            - name: AUTH0_CLIENT_SECRET
              value: X5f4yOvgHmQlJd06jar7CFdq4zkkqaguGUgNEp904WFL2lr121QSS-Z6_qLw7RhZ
            - name: ORDER_BASE_URL
              value: 'http://pizza-castle-ordering-service.default.svc.cluster.local:5002/api/v1/order'
            - name: MENU_BASE_URL
              value: 'http://pizza-castle-menu-service.default.svc.cluster.local:5000/api/v1/menu'
