apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-castle-ordering-service
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: pizza-castle-ordering-service
annotations:
  fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: pizza-castle-ordering-service
  replicas: 1
  template:
    metadata:
      labels:
        app: pizza-castle-ordering-service
    spec:
      containers:
        - name: ordering-service
          image: gayankanishka/pizza-castle-ordering-service:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
          env:
            - name: UseInMemoryDatabase
              valueFrom:
                configMapKeyRef:
                  name: use-in-memory-db
                  key: USE_IN_MEMORY_DB
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: asp-net-core-env
                  key: ASPNETCORE_ENVIRONMENT
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 5002
