name: 'Terraform DEV CI/CD'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform-ci-cd:
    uses: gayankanishka/pizza-castle-infrastructure/.github/workflows/terraform-core.yml@main
    with:
      workspace: dev
    secrets:
      token: ${{ secrets.TF_API_TOKEN }}
