name: Terraform Core CI/CD

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  terraform-ci-cd:
    name: 'Core CI/CD'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './terraform'
    env:
      TF_WORKSPACE: ${{ inputs.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.token }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
